// Code generated by mockery v2.12.1. DO NOT EDIT.

package mock

import (
	execution "github.com/onflow/flow-go/engine/execution"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Uploader is an autogenerated mock type for the Uploader type
type Uploader struct {
	mock.Mock
}

// Upload provides a mock function with given fields: computationResult
func (_m *Uploader) Upload(computationResult *execution.ComputationResult) error {
	ret := _m.Called(computationResult)

	var r0 error
	if rf, ok := ret.Get(0).(func(*execution.ComputationResult) error); ok {
		r0 = rf(computationResult)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUploader creates a new instance of Uploader. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewUploader(t testing.TB) *Uploader {
	mock := &Uploader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
